// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {datatransfers} from '../models';

export function ProcessVideosFromUpload(arg1:Array<string>,arg2:Array<string>,arg3:string):Promise<{[key: string]: string}>;

export function UpscaleVideoWithRealESRGAN(arg1:datatransfers.VideoUpscalerRequest):Promise<void>;
