// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelProcessing() {
  return window['go']['main']['App']['CancelProcessing']();
}

export function ProcessVideosFromUpload(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessVideosFromUpload'](arg1, arg2, arg3);
}
