// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {datatransfers} from '../models';

export function CancelProcessing():Promise<void>;

export function CleanupRootTempFolder():Promise<void>;

export function ExtractFFmpeg():Promise<void>;

export function ExtractRealEsrgan():Promise<void>;

export function GetVideoInfo(arg1:string):Promise<datatransfers.VideoInfoResponse>;

export function OpenOutputFolder():Promise<void>;

export function ProcessVideosFromUpload(arg1:Array<datatransfers.InputFileRequest>):Promise<{[key: string]: string}>;

export function ShutdownComputer():Promise<void>;
