// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFiles() {
  return window['go']['main']['Upscaler']['OpenFiles']();
}

export function ProcessVideos(arg1, arg2) {
  return window['go']['main']['Upscaler']['ProcessVideos'](arg1, arg2);
}
