// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFiles():Promise<Array<string>>;

export function ProcessVideosFromUpload(arg1:Array<string>,arg2:Array<string>,arg3:string):Promise<{[key: string]: string}>;
