// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFile() {
  return window['go']['main']['Upscaler']['OpenFile']();
}

export function Process(arg1, arg2) {
  return window['go']['main']['Upscaler']['Process'](arg1, arg2);
}
