// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFiles():Promise<Array<string>>;

export function ProcessVideos(arg1:Array<string>,arg2:string):Promise<{[key: string]: string}>;
