name: Build and Release Wails App

on:
  push:
    tags:
      - 'v*'  # Runs only when you push a version tag like v1.0.0

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write  
    steps:
      - name: Checkout code with LFS
        uses: actions/checkout@v4
        with:
          lfs: true  # Ensure Git LFS files are fetched

      - name: Pull Git LFS files
        run: git lfs pull  # Fetch all LFS-tracked files (e.g., embeds/ffmpeg)

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Dependencies
        run: npm install
        working-directory: frontend

      - name: Build Wails App
        run: wails build -platform windows/amd64 --clean

      - name: Compress to ZIP
        run: Compress-Archive -Path build/bin/*.exe -DestinationPath build/bin/RevivePixels.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wails-app
          path: build/bin/RevivePixels.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/bin/RevivePixels.zip
          token: ${{ secrets.GITHUB_TOKEN }}
