name: Build and Release Wails App

on:
  push:
    tags:
      - 'v*'  # Runs only when you push a version tag like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Dependencies
        run: npm install
        working-directory: frontend

      - name: Build Wails App
        run: wails build -platform windows/amd64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wails-app
          path: build/bin/*.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/bin/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
